---
- hosts: 172.31.86.216
  tasks:
  - name:
    apt:
     name: git
     state: present
  
  - name:
    apt:
     name: tree
     state: present

  - name:
    apt:
     name: wget
     state: present
 