---
- hosts: 172.31.86.216
  tasks:
  
    apt:
     name: git
     state: present
  
  - name: install tree on nodes
    apt:
     name: tree
     state: present

  - name: install wget
    apt:
     name: wget
     state: present
 